name: Deploy Model

on:
  workflow_dispatch:
    inputs:
      api_version:
        description: 'Version of the API to deploy'
        required: true
        default: 'latest'
      model_release:
        description: 'Version of the model to deploy'
        required: true
        default: 'latest'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: API_VERSION
        run: |
          echo "API_VERSION >> $GITHUB_ENV
          echo "MODEL_VERSION >> $GITHUB_ENV

      - name: Deploy to Render
        env:
          MODEL_RELEASE: ${{ inputs.model_release }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ inputs.api_version }}" != "latest" ]]; then
            git checkout ${{ inputs.api_version }}
          fi
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}